name: xnet-start

# corresponds to
# 12:00AM EST / 9pm PST
# 8AM EST / 5AM PST
# 4PM EST / 1PM PST
on:
  schedule:
    - cron: "0 4 * * *"
    - cron: "0 12 * * *"
    - cron: "0 20 * * *"
  workflow_dispatch:

permissions:
  contents: read

env:
  HCLOUD_TOKEN: ${{ secrets.HCLOUD_TOKEN }}
  SERVER_NAME: xnet-public
  FLOATING_IP_NAME: xmtp-migration-test
  SSH_KEY_NAME: insipx-hetzner

jobs:
  deploy:
    runs-on: ubuntu-latest
    timeout-minutes: 30

    steps:
      - uses: actions/checkout@v4

      - uses: cachix/install-nix-action@v27
        with:
          nix_path: nixpkgs=channel:nixos-25.11

      - uses: cachix/cachix-action@v17
        with:
          name: xmtp
          authToken: "${{ secrets.CACHIX_AUTH_TOKEN }}"

      - uses: nicknovitski/nix-develop@v1

      - name: Setup SSH key
        run: |
          mkdir -p ~/.ssh
          echo "${{ secrets.SSH_PRIVATE_KEY }}" > ~/.ssh/xnet
          chmod 600 ~/.ssh/xnet

      - name: Deploy
        run: |
          chmod +x ./dev/provision
          SSH_KEY_PATH=~/.ssh/xnet ./dev/provision
